### PR TITLE
pipfile: update Python and pip version

### PR DESCRIPTION
**Pull request by aliculPix4D**
pipfile: update Python and pip version

In https://github.com/cf-platform-eng/concourse-pypi-resource/pull/115#issue-1288808151 we have pinned both Python version in Dockerfile and pip version in Pipfile. This ensured that correct pip version was deployed with the Docker image. 

Now its seems its time to upgrade. At the time, I was reluctant to do it because API changed for some functions with newer pip versions.

Main reason for this change is because our developers started to upgrade their projects to Python >=3.10 and we started to see some packages that are successfully uploaded to Artifactory, but could not be found in subsequent implicit get step even though resource configuration was correct.
i.e following package was successful uploaded:
`pkg-name-2.0.0b11-cp310-cp310-linux_x86_64.whl version 2.0.0b11`
but failed in the next implicit get step with:
```
-- Failed retrying after 20 tries with a 3.000000 second delay
Traceback (most recent call last):
  File "/opt/resource/in", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pypi_resource/in_.py", line 107, in main
    response = in_(destdir, sys.stdin)
  File "/usr/local/lib/python3.9/site-packages/pypi_resource/in_.py", line 82, in in_
    response = download(resconfig, destdir)
  File "/usr/local/lib/python3.9/site-packages/pypi_resource/retry.py", line 21, in wrapper
    raise e
  File "/usr/local/lib/python3.9/site-packages/pypi_resource/retry.py", line 15, in wrapper
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pypi_resource/in_.py", line 58, in download_version
    raise ValueError("No matching packages found.")
ValueError: No matching packages found.
```
there was no such issues after I upgraded python and pip.

### CODE REVIEW

**Comment by aliculPix4D** [comment]
@mboldt Can you please review this PR when you catch the time? Thanks

**Comment by aliculPix4D** [comment]
@mboldt ping

**Comment by aliculPix4D** [comment]
@mboldt just to check if you had the time to check this PR. Thanks.

**Comment by mboldt** [comment]
So sorry - I have changed jobs and no longer have write access to this repository. Would you be interested in forking and owning this?

**Comment by aliculPix4D** [comment]
> So sorry - I have changed jobs and no longer have write access to this repository. Would you be interested in forking and owning this?

Hi @mboldt, to unblock our developers we have recently forked this repo. The fork is of course public: https://github.com/Pix4D/concourse-pypi-resource but we publish our Docker image only internally. 
We have already merged this fix in there, so anyone is free to use it.

**Pull request closed without merging**
