### PR TITLE
get: create version file [fixes #2]

### LINKED ISSUE #2: in: /version file
Could we please add a `version` file in the resource folder so it can be consumed by subsequent steps in the pipeline?

An example of another resource having this behaviour is https://github.com/concourse/github-release-resource#in-fetch-assets-from-a-release

### PR DESCRIPTION
**Pull request by drnic**
@mboldt I have not tested this due to #3 - I'm not sure how to build the docker image.

So this is a guesstimate of what Python might work here :)

### CODE REVIEW

**Comment by mboldt** [comment]
I gave it a quick test, and it looks good. Thank you, @drnic!

**Comment by mboldt** [comment]
I'll push this to docker hub today.

**Comment by mboldt** [comment]
Pushed to docker hub.

**Comment by drnic** [comment]
thanks @mbolt!

**Comment by drnic** [comment]
Fantastic, this was the only thing needed for https://ci.starkandwayne.com/teams/main/pipelines/sample-python-flask-app-boshrelease/jobs/pip/builds/2 to work. Excellent. Now I can begin watching many pypi packages. Bwahaha.

**Pull request merged**
